// Code generated by go-swagger; DO NOT EDIT.

package project

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// AddProjectHandlerFunc turns a function with the right signature into a add project handler
type AddProjectHandlerFunc func(AddProjectParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn AddProjectHandlerFunc) Handle(params AddProjectParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// AddProjectHandler interface for that can handle valid add project params
type AddProjectHandler interface {
	Handle(AddProjectParams, interface{}) middleware.Responder
}

// NewAddProject creates a new http.Handler for the add project operation
func NewAddProject(ctx *middleware.Context, handler AddProjectHandler) *AddProject {
	return &AddProject{Context: ctx, Handler: handler}
}

/*
	AddProject swagger:route POST /project project addProject

Add a new project of a partner
*/
type AddProject struct {
	Context *middleware.Context
	Handler AddProjectHandler
}

func (o *AddProject) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewAddProjectParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
