// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AchievementRequest achievement request
//
// swagger:model AchievementRequest
type AchievementRequest struct {

	// description
	// Example: GTA 5
	Description string `json:"description,omitempty"`

	// image
	// Example: example.com
	Image string `json:"image,omitempty"`

	// sku
	// Example: X-DKK-KDM
	Sku string `json:"sku,omitempty"`
}

// Validate validates this achievement request
func (m *AchievementRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this achievement request based on context it is used
func (m *AchievementRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AchievementRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AchievementRequest) UnmarshalBinary(b []byte) error {
	var res AchievementRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
