// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Achievement achievement
//
// swagger:model Achievement
type Achievement struct {

	// description
	// Example: GTA 5
	Description string `json:"description,omitempty"`

	// id
	// Example: f74687fa-2df7-450e-8c31-993695dcebf7
	// Format: uuid
	ID strfmt.UUID `json:"id,omitempty"`

	// image
	// Example: example.com
	Image string `json:"image,omitempty"`

	// sku
	// Example: X-DKK-KDM
	Sku string `json:"sku,omitempty"`
}

// Validate validates this achievement
func (m *Achievement) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Achievement) validateID(formats strfmt.Registry) error {
	if swag.IsZero(m.ID) { // not required
		return nil
	}

	if err := validate.FormatOf("id", "body", "uuid", m.ID.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this achievement based on context it is used
func (m *Achievement) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Achievement) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Achievement) UnmarshalBinary(b []byte) error {
	var res Achievement
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
