// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PlayerRequest player request
//
// swagger:model PlayerRequest
type PlayerRequest struct {

	// wallet address
	// Example: ba4TrH8sNRzQfFhJH8mR
	WalletAddress string `json:"wallet_address,omitempty"`
}

// Validate validates this player request
func (m *PlayerRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this player request based on context it is used
func (m *PlayerRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PlayerRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PlayerRequest) UnmarshalBinary(b []byte) error {
	var res PlayerRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
