// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ProjectRequest project request
//
// swagger:model ProjectRequest
type ProjectRequest struct {

	// name
	// Example: GTA 5
	// Required: true
	Name *string `json:"name"`

	// webhook url
	// Example: example.com
	// Required: true
	WebhookURL *string `json:"webhook_url"`
}

// Validate validates this project request
func (m *ProjectRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateWebhookURL(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ProjectRequest) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

func (m *ProjectRequest) validateWebhookURL(formats strfmt.Registry) error {

	if err := validate.Required("webhook_url", "body", m.WebhookURL); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this project request based on context it is used
func (m *ProjectRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ProjectRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ProjectRequest) UnmarshalBinary(b []byte) error {
	var res ProjectRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
