// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ProjectResponse project response
//
// swagger:model ProjectResponse
type ProjectResponse struct {

	// api key
	// Example: abcdef123
	APIKey string `json:"api_key,omitempty"`

	// id
	ID string `json:"id,omitempty"`
}

// Validate validates this project response
func (m *ProjectResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this project response based on context it is used
func (m *ProjectResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ProjectResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ProjectResponse) UnmarshalBinary(b []byte) error {
	var res ProjectResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
