// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// WebhookEvent webhook event
//
// swagger:model WebhookEvent
type WebhookEvent struct {

	// event id
	// Example: 5e6890cc-c3a1-4c26-b269-b55e715c09b8
	// Format: uuid
	EventID strfmt.UUID `json:"event_id,omitempty"`

	// player id
	// Example: 5e6890cc-c3a1-4c26-b269-b55e715c09b8
	// Format: uuid
	PlayerID strfmt.UUID `json:"player_id,omitempty"`
}

// Validate validates this webhook event
func (m *WebhookEvent) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEventID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePlayerID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *WebhookEvent) validateEventID(formats strfmt.Registry) error {
	if swag.IsZero(m.EventID) { // not required
		return nil
	}

	if err := validate.FormatOf("event_id", "body", "uuid", m.EventID.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *WebhookEvent) validatePlayerID(formats strfmt.Registry) error {
	if swag.IsZero(m.PlayerID) { // not required
		return nil
	}

	if err := validate.FormatOf("player_id", "body", "uuid", m.PlayerID.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this webhook event based on context it is used
func (m *WebhookEvent) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *WebhookEvent) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *WebhookEvent) UnmarshalBinary(b []byte) error {
	var res WebhookEvent
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
