// Code generated by go-swagger; DO NOT EDIT.

package player

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"ta4/mod/internal/server/models"
)

// PostPlayerCreatedCode is the HTTP code returned for type PostPlayerCreated
const PostPlayerCreatedCode int = 201

/*
PostPlayerCreated Player created

swagger:response postPlayerCreated
*/
type PostPlayerCreated struct {

	/*
	  In: Body
	*/
	Payload *models.Player `json:"body,omitempty"`
}

// NewPostPlayerCreated creates PostPlayerCreated with default headers values
func NewPostPlayerCreated() *PostPlayerCreated {

	return &PostPlayerCreated{}
}

// WithPayload adds the payload to the post player created response
func (o *PostPlayerCreated) WithPayload(payload *models.Player) *PostPlayerCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post player created response
func (o *PostPlayerCreated) SetPayload(payload *models.Player) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostPlayerCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
