// Code generated by go-swagger; DO NOT EDIT.

package player

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostPlayerHandlerFunc turns a function with the right signature into a post player handler
type PostPlayerHandlerFunc func(PostPlayerParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostPlayerHandlerFunc) Handle(params PostPlayerParams) middleware.Responder {
	return fn(params)
}

// PostPlayerHandler interface for that can handle valid post player params
type PostPlayerHandler interface {
	Handle(PostPlayerParams) middleware.Responder
}

// NewPostPlayer creates a new http.Handler for the post player operation
func NewPostPlayer(ctx *middleware.Context, handler PostPlayerHandler) *PostPlayer {
	return &PostPlayer{Context: ctx, Handler: handler}
}

/*
	PostPlayer swagger:route POST /player player postPlayer

Save new player
*/
type PostPlayer struct {
	Context *middleware.Context
	Handler PostPlayerHandler
}

func (o *PostPlayer) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostPlayerParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
