// Code generated by go-swagger; DO NOT EDIT.

package achievement

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"ta4/mod/internal/server/models"
)

// PostAchievementCreatedCode is the HTTP code returned for type PostAchievementCreated
const PostAchievementCreatedCode int = 201

/*
PostAchievementCreated Achievement created

swagger:response postAchievementCreated
*/
type PostAchievementCreated struct {

	/*
	  In: Body
	*/
	Payload *models.Achievement `json:"body,omitempty"`
}

// NewPostAchievementCreated creates PostAchievementCreated with default headers values
func NewPostAchievementCreated() *PostAchievementCreated {

	return &PostAchievementCreated{}
}

// WithPayload adds the payload to the post achievement created response
func (o *PostAchievementCreated) WithPayload(payload *models.Achievement) *PostAchievementCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post achievement created response
func (o *PostAchievementCreated) SetPayload(payload *models.Achievement) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostAchievementCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
