// Code generated by go-swagger; DO NOT EDIT.

package achievement

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostAchievementHandlerFunc turns a function with the right signature into a post achievement handler
type PostAchievementHandlerFunc func(PostAchievementParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostAchievementHandlerFunc) Handle(params PostAchievementParams) middleware.Responder {
	return fn(params)
}

// PostAchievementHandler interface for that can handle valid post achievement params
type PostAchievementHandler interface {
	Handle(PostAchievementParams) middleware.Responder
}

// NewPostAchievement creates a new http.Handler for the post achievement operation
func NewPostAchievement(ctx *middleware.Context, handler PostAchievementHandler) *PostAchievement {
	return &PostAchievement{Context: ctx, Handler: handler}
}

/*
	PostAchievement swagger:route POST /achievement achievement postAchievement

Save new achievement
*/
type PostAchievement struct {
	Context *middleware.Context
	Handler PostAchievementHandler
}

func (o *PostAchievement) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostAchievementParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
