// Code generated by go-swagger; DO NOT EDIT.

package event

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"ta4/mod/internal/server/models"
)

// PostEventCreatedCode is the HTTP code returned for type PostEventCreated
const PostEventCreatedCode int = 201

/*
PostEventCreated Event created

swagger:response postEventCreated
*/
type PostEventCreated struct {

	/*
	  In: Body
	*/
	Payload *models.Event `json:"body,omitempty"`
}

// NewPostEventCreated creates PostEventCreated with default headers values
func NewPostEventCreated() *PostEventCreated {

	return &PostEventCreated{}
}

// WithPayload adds the payload to the post event created response
func (o *PostEventCreated) WithPayload(payload *models.Event) *PostEventCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post event created response
func (o *PostEventCreated) SetPayload(payload *models.Event) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostEventCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
