// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Swagger T4A
//
//	Schemes:
//	  http
//	  https
//	Host: localhost
//	BasePath: /
//	Version: 1.0.0
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
