// Code generated by go-swagger; DO NOT EDIT.

package trigger

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"ta4/mod/internal/server/models"
)

// PostTriggerCreatedCode is the HTTP code returned for type PostTriggerCreated
const PostTriggerCreatedCode int = 201

/*
PostTriggerCreated Trigger created

swagger:response postTriggerCreated
*/
type PostTriggerCreated struct {

	/*
	  In: Body
	*/
	Payload *models.Trigger `json:"body,omitempty"`
}

// NewPostTriggerCreated creates PostTriggerCreated with default headers values
func NewPostTriggerCreated() *PostTriggerCreated {

	return &PostTriggerCreated{}
}

// WithPayload adds the payload to the post trigger created response
func (o *PostTriggerCreated) WithPayload(payload *models.Trigger) *PostTriggerCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post trigger created response
func (o *PostTriggerCreated) SetPayload(payload *models.Trigger) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostTriggerCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
